### ISSUE TITLE
[1.0] Select Element background is black when DevTools is in Device Mode 

### ISSUE THREAD

**Issue by abhi1-g** [micjamking/devtools-author#105] opened 2016-02-03 20:17 UTC
When DevTools is in Device Mode a large portion of the Select Element dropdown background is black 
![light](https://cloud.githubusercontent.com/assets/8082746/12795625/dde07700-cae0-11e5-81ba-b1aef32ca375.jpg)
It happens with all light and dark themes 
![dark](https://cloud.githubusercontent.com/assets/8082746/12795659/03068362-cae1-11e5-8d0b-984d31aff849.jpg)

**Comment by micjamking** [comment] 2016-02-03 21:43
Hi @abhi1-g, thanks for bringing this to my attention. Just so I can confirm, is this a Windows machine?

Since I'm on a Mac, this issue is not present (OSX uses a system default style for select menu pop-ups).

![screen shot 2016-02-03 at 11 24 30 am](https://cloud.githubusercontent.com/assets/651702/12797625/fc9d0140-ca68-11e5-94eb-1a92c1e80f1f.png)

![screen shot 2016-02-03 at 11 23 06 am](https://cloud.githubusercontent.com/assets/651702/12797635/0342af36-ca69-11e5-8bdb-94d4f334405e.png)

Is it possible for you to debug the select menu on the page where this issue is occurring  (with shadow DOM enabled in DevTools) and see what styles could be overriding and/or causing conflict?

Thanks!

**Comment by bolensmichael** [comment] 2016-02-04 19:11
I can confirm this is happening on PC only. Works fine on my macbook, but on my desktop it shows up strangely.
<img width="450" alt="2016-02-04 13_10_06-edit fiddle - jsfiddle" src="https://cloud.githubusercontent.com/assets/1218380/12826471/c027a0e8-cb40-11e5-9462-6848e6deb91b.png">

**Comment by micjamking** [comment] 2016-02-14 00:36
@abhi1-g & @bolensmichael I don't want to let this issue drag out, but I do not have immediate access to a Windows machine so I need additional support for this. Is it possible for either of you to debug the select menu on the page where this issue is occurring (with shadow DOM enabled in DevTools) and see what styles could be overriding and/or causing conflict?

Also, what Windows OS version, Chrome version, and DevTools Author version are you both experiencing this issue on?

**Comment by bolensmichael** [comment] 2016-02-15 21:13
@micjamking I have Win 10 64-bit latest Chrome and DevTools. At first glance I saw nothing that would be causing the issue. I will try to play with it more tonight as remoting into my PC and trying to debug is not working very well. If you have anything specific you'd like me to look for too, feel free to point it out! Otherwise I will be enabling/disabling styles until I find the culprit :)

**Comment by micjamking** [comment] 2016-03-07 22:11
Hi @bolensmichael, I'm just following up to see if you were able to discover anything while debugging the issue on your end?

**Comment by abhi1-g** [comment] 2016-03-09 05:51
The Device Mode has been updated with new UI in the latest Chrome 49 Update and the Issue is resolved in Chrome 49 
![screenshot](https://cloud.githubusercontent.com/assets/8082746/13626559/13aab706-e5e9-11e5-857a-ea3f11cc6f6e.jpg)

**Comment by micjamking** [comment] 2016-03-09 21:05
Hey @abhi1-g, thanks for following up! 

It seems like the issue may have been related to DevTools itself rather than my plugin; I'm going to close this issue for now, but feel free to comment if you experience any other issues and I will reopen.

Mahalo!
:v:

**Closed by micjamking** 2016-03-09 21:05 UTC
Labels: bug, high, invalid, Windows
