### ISSUE TITLE
Tab titles in Devtools are getting cropped

### ISSUE THREAD

**Issue by thisizkp** [micjamking/devtools-author#150] opened 2016-10-25 09:10 UTC
<img width="433" alt="screen shot 2016-10-25 at 14 37 45" src="https://cloud.githubusercontent.com/assets/4737336/19679777/da52fe7c-9ac0-11e6-8bbc-4a0bc0eacf19.png">

**Comment by edheltzel** [comment] 2016-12-21 21:19
I can confirm this _(and this is **probably** related to OR a duplicate of #149)_

 ![image](http://rdm.d.pr/652M+)

**I'm also on Chrome 55 ↑**
![image](http://rdm.d.pr/9RjH+)

**Comment by swedkg** [comment] 2017-05-20 16:47
The same happens on 58.0.3029.110 (64-bit)

**Comment by DrianHillman** [comment] 2017-07-04 02:57
Love DevTools Author but I've noticed this as well for quite some time. Here comes a PR to remedy this, @micjamking!

**Closed as completed** 2020-05-16 14:10 UTC
