### ISSUE TITLE
Monokai theme color issue in console

### ISSUE THREAD

**Issue by besir** [micjamking/devtools-author#96] opened 2016-01-31 20:42 UTC
After throw exception is first message not readable (bad color)

Screenshots:
[one](http://i65.tinypic.com/fnbbmc.png)

[showed text](http://i67.tinypic.com/2vafmo2.png)

**Comment by micjamking** [comment] 2016-02-01 02:56
Hey @besir, thank you for catching that! 

I just recently made fixes for console warnings and it looks like they may have impacted the error logging unintentionally. I'll try to address this ASAP!

Thanks!

**Comment by besir** [comment] 2016-02-01 07:09
Thx!

**Comment by drfisher** [comment] 2016-02-01 15:57
I have the same issue. To reproduce it just paste in a console this code

`throw new Error('Error message');`

**Comment by micjamking** [comment] 2016-02-02 08:41
@besir / @drfisher this is resolved in v0.5.5 5ba3d18

![screen shot 2016-02-01 at 10 37 00 pm](https://cloud.githubusercontent.com/assets/651702/12743873/e5a20b14-c934-11e5-8747-e97ca904af44.png)

**Closed by micjamking** 2016-02-02 08:41 UTC

**Comment by besir** [comment] 2016-02-07 20:00
+1
